<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/MultiIndex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### Series is 1D and DataFrames are 2D objects

- But why?
- And what exactly is index?

In [2]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [3]:
# The problem?
a['cse']

KeyError: 'cse'

In [4]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [6]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [7]:
multiindex.levels[1]
multiindex.levels[0]

Index(['cse', 'ece'], dtype='object')

In [15]:
# 2. pd.MultiIndex.from_product()
a = pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022],[1,2,3,4]])
len(a)

32

In [19]:
s = pd.Series(np.arange(0, 32),index=a)
s

cse  2019  1     0
           2     1
           3     2
           4     3
     2020  1     4
           2     5
           3     6
           4     7
     2021  1     8
           2     9
           3    10
           4    11
     2022  1    12
           2    13
           3    14
           4    15
ece  2019  1    16
           2    17
           3    18
           4    19
     2020  1    20
           2    21
           3    22
           4    23
     2021  1    24
           2    25
           3    26
           4    27
     2022  1    28
           2    29
           3    30
           4    31
dtype: int64

In [20]:
# how to fetch items from such a series
s['cse']

2019  1     0
      2     1
      3     2
      4     3
2020  1     4
      2     5
      3     6
      4     7
2021  1     8
      2     9
      3    10
      4    11
2022  1    12
      2    13
      3    14
      4    15
dtype: int64

In [21]:
# a logical question to ask

In [39]:
# unstack
temp = s.unstack()
a = temp.unstack()
b= a.unstack()
type(s)
type(temp)
type(b)

pandas.core.series.Series

In [41]:
# stack
a= temp.stack()
a

cse  2019  1     0
           2     1
           3     2
           4     3
     2020  1     4
           2     5
           3     6
           4     7
     2021  1     8
           2     9
           3    10
           4    11
     2022  1    12
           2    13
           3    14
           4    15
ece  2019  1    16
           2    17
           3    18
           4    19
     2020  1    20
           2    21
           3    22
           4    23
     2021  1    24
           2    25
           3    26
           4    27
     2022  1    28
           2    29
           3    30
           4    31
dtype: int64

In [42]:
type(a)

pandas.core.series.Series

In [43]:
# Then what was the point of multiindex series?

In [44]:
# multiindex dataframe

In [45]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [48]:
a=input('enter dept:  ')
b=int(input('enter year:  '))
branch_df1.loc[(a,b)]

enter dept:  cse
enter year:  2021

avg_package    5
students       6
Name: (cse, 2021), dtype: int64

In [49]:
branch_df1['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [50]:
# Are columns really different from index?

In [51]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [66]:
branch_df2.loc[2019]
branch_df2['delhi']
branch_df2['delhi']['students']
branch_df2.loc[2019, ('mumbai')]

avg_package    0
students       0
Name: 2019, dtype: int64