<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

### Series from lists

In [2]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [4]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [5]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [6]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

### Series from dict

In [9]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}


marks_series = pd.Series(marks,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

### Series Attributes

In [10]:
# size
marks_series.size

4

In [11]:
# dtype
marks_series.dtype

dtype('int64')

In [12]:
marks_series.name

'nitish ke marks'

In [14]:
# is_unique
marks_series.is_unique

# pd.Series([1,1,2,3,4,5]).is_unique

True

In [15]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [16]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
# values
marks_series.values

array([ 67,  57,  89, 100])

In [20]:
runs_ser.values

array([ 13,  24,  56,  78, 100])

### Series using read_csv

In [21]:
pd.read_csv('/content/subs.csv')

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [22]:
type(pd.read_csv('/content/subs.csv'))

pandas.core.frame.DataFrame

In [41]:
subs = pd.read_csv('/content/subs.csv').squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [42]:
type(subs)

pandas.core.series.Series

In [49]:
# with 2 cols
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no').squeeze("columns")
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [50]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie').squeeze("columns")
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series methods

In [51]:
# head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [52]:
vk.head(3)

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [57]:
vk.tail(10)

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [56]:
# sample
movies.sample(5)

movie
Phoonk 2                           Sudeep
Boom (film)              Amitabh Bachchan
Raja Natwarlal              Emraan Hashmi
Junooniyat                  Pulkit Samrat
Accident on Hill Road       Farooq Shaikh
Name: lead, dtype: object

In [58]:
# value_counts -> movies
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [60]:
# sort_values -> inplace
vk.sort_values(ascending=False)

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [63]:
vk.sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [65]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=False,inplace=True)

In [66]:
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [77]:
vk = vk.sort_values(ascending=False)

In [78]:
vk

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

### Series Maths Methods

In [79]:
# count
vk.count()

np.int64(215)

In [80]:
# sum -> product
subs.sum()

np.int64(49510)

In [82]:
subs.product()

np.int64(0)

In [89]:
# mean -> median -> mode -> std -> var

print(subs.mean())
print(vk.median())
print(movies.mode())
print(vk.std())
print(vk.var())

135.64383561643837
24.0
0    Akshay Kumar
Name: lead, dtype: object
26.22980132830278
688.0024777222343

In [92]:
#min/max
print(subs.max())
print(subs.min())

396
33

In [94]:
#describe
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

### Series Indexing

In [95]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

0    12
1    13
2    14
3    35
4    46
5    57
6    58
7    79
8     9
dtype: int64

In [96]:
x[3]

np.int64(35)

In [97]:
# negative indexing
x[-1]

KeyError: -1

In [103]:
pd.Series(movies)

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [104]:
movies[0]

/tmp/ipykernel_5831/3901301928.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movies[0]

'Meghan Jadhav'

In [105]:
movies[-1]

/tmp/ipykernel_5831/2731571422.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movies[-1]

'Rajniesh Duggall'

In [106]:
vk[-1]

KeyError: -1

In [107]:
#SLicing
vk[:10]

match_no
128    113
126    109
123    108
120    100
164    100
82      99
81      93
145     92
178     90
160     84
Name: runs, dtype: int64

In [108]:
movies[-5:]

movie
2 States (2014 film)          Arjun Kapoor
1971 (2007 film)            Manoj Bajpayee
1920: The Evil Returns         Vicky Ahuja
1920: London                 Sharman Joshi
1920 (film)               Rajniesh Duggall
Name: lead, dtype: object

In [109]:
movies[::2]

movie
Zor Lagaa Ke...Haiya!         Meghan Jadhav
Zindagi Tere Naam        Mithun Chakraborty
Zindagi 50-50                   Veena Malik
Zinda (film)                    Sanjay Dutt
Zid (2014 film)              Mannara Chopra
                                ...
3 Storeys                       Aisha Ahmed
3 Deewarein                Naseeruddin Shah
22 Yards                        Barun Sobti
1971 (2007 film)             Manoj Bajpayee
1920: London                  Sharman Joshi
Name: lead, Length: 750, dtype: object

In [111]:
#fancy indexing
vk[[2,4,6,8]]

match_no
2    23
4    12
6     9
8     0
Name: runs, dtype: int64

In [113]:
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [114]:
# indexing with labels -> fancy indexing
movies['1920: The Evil Returns']

'Vicky Ahuja'

### Editing Series

In [115]:
# using indexing
marks_series[1] = 100
marks_series

/tmp/ipykernel_5831/3621369324.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

maths       67
english    100
science     89
hindi      100
Name: nitish ke marks, dtype: int64

In [116]:
# what if an index does not exist
marks_series['evs'] = 100

In [117]:
marks_series

maths       67
english    100
science     89
hindi      100
evs        100
Name: nitish ke marks, dtype: int64

In [118]:
# slicing
runs_ser[2:4] = [100,100]
runs_ser

0     13
1     24
2    100
3    100
4    100
dtype: int64

In [119]:
runs

[13, 24, 56, 78, 100]

In [120]:
# fancy indexing
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

0      0
1     24
2    100
3      0
4      0
dtype: int64

In [121]:
# using index label
movies['2 States (2014 film)'] = 'Alia Bhatt'
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)                Alia Bhatt
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object