<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

### Series from lists

In [2]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [4]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [5]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [6]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

### Series from dict

In [9]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}


marks_series = pd.Series(marks,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

### Series Attributes

In [10]:
# size
marks_series.size

4

In [11]:
# dtype
marks_series.dtype

dtype('int64')

In [12]:
marks_series.name

'nitish ke marks'

In [14]:
# is_unique
marks_series.is_unique

# pd.Series([1,1,2,3,4,5]).is_unique

True

In [15]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [16]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
# values
marks_series.values

array([ 67,  57,  89, 100])

In [20]:
runs_ser.values

array([ 13,  24,  56,  78, 100])

### Series using read_csv