<a href="https://colab.research.google.com/github/akritivishwakarma2007/DE-journey/blob/main/Pivot_Table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pivot Table

The pivot table takes simple column-wise data as input, and groups the entries into a two-dimensional table that provides a multidimensional summarization of the data.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.groupby('sex')['total_bill'].mean()

/tmp/ipykernel_8455/3379495421.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['total_bill'].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [ ]:
df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

/tmp/ipykernel_8455/884363850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill')

/tmp/ipykernel_8455/4282385320.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
# aggfunc
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='mean')

/tmp/ipykernel_8455/1751944094.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='mean')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='max')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='min')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='count')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='median')
df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='sum')

/tmp/ipykernel_8455/3903295305.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='max')
/tmp/ipykernel_8455/3903295305.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='min')
/tmp/ipykernel_8455/3903295305.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='count')
/tmp/ipykernel_8455/3903295305.py:4: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='median')
/tmp/ipykernel_8455/3903295305.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns= 'smoker', values= 'total_bill', aggfunc='sum')

smoker      Yes       No
sex
Male    1337.07  1919.75
Female   593.27   977.68

In [ ]:
# all cols together
df.pivot_table(index='sex',columns='smoker')['size']

/tmp/ipykernel_8455/3226264718.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker')['size']

TypeError: category dtype does not support aggregation 'mean'

In [ ]:
# all cols together
df.pivot_table(index='sex',columns='smoker', values='size')

/tmp/ipykernel_8455/1002198549.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex',columns='smoker', values='size')

smoker       Yes        No
sex
Male    2.500000  2.711340
Female  2.242424  2.592593